import '@mdi/font/css/materialdesignicons.css';
import 'vuetify/styles';
import { createVuetify } from 'vuetify';
// Colliers-ის ლოგოზე დაფუძნებული Vuetify 3 Theme (Light & Dark)

// Colliers-ის ლოგოზე დაფუძნებული Vuetify 3 Theme (Light & Dark)

export default createVuetify({
  theme:{
    defaultTheme: 'light',
    themes:{
      light: {
        dark: false,
        colors: {
          background: '#fdfcf5',
          surface: '#f5f4ec',
          'surface-bright': '#d4d3de',
          'surface-variant': '#e2e1ec',
          'on-surface-variant': '#45464f',
          primary: '#415aaa',
          'primary-darken-1': '#264190',
          secondary: '#705d00',
          'secondary-darken-1': '#554600',
          error: '#bf0023',
          info: '#0061a4',
          success: '#006e1c',
          warning: '#FB8C00',
          'on-primary': '#ffffff',
          'primary-container': '#dce1ff',
          'on-primary-container': '#00164e',
          'on-secondary': '#ffffff',
          'secondary-container': '#ffe171',
          'on-secondary-container': '#221b00',
          tertiary: '#00658d',
          'on-tertiary': '#ffffff',
          'tertiary-container': '#c6e7ff',
          'on-tertiary-container': '#001e2d',
          'on-background': '#1b1c18',
          'on-surface': '#1f201c',
          'on-surface-bright': '#4a4b53',
          'on-error': '#ffffff',
          'error-container': '#ffdad7',
          'on-error-container': '#410006',
          'on-success': '#ffffff',
          'success-container': '#94f990',
          'on-success-container': '#002204',
          warn: '#8f4e00',
          'on-warn': '#ffffff',
          'warn-container': '#ffdcc2',
          'on-warn-container': '#2e1500',
          'on-info': '#ffffff',
          'info-container': '#d1e4ff',
          'on-info-container': '#001d36',
        },
        variables: {
          'border-color': '#000000',
          'border-opacity': 0.12,
          'high-emphasis-opacity': 0.87,
          'medium-emphasis-opacity': 0.6,
          'disabled-opacity': 0.38,
          'idle-opacity': 0.04,
          'hover-opacity': 0.04,
          'focus-opacity': 0.12,
          'selected-opacity': 0.08,
          'activated-opacity': 0.12,
          'pressed-opacity': 0.12,
          'dragged-opacity': 0.08,
          'theme-kbd': '#212529',
          'theme-on-kbd': '#FFFFFF',
          'theme-code': '#F5F5F5',
          'theme-on-code': '#000000',
        },
      },
      dark: {
        dark: true,
        colors: {
          background: '#1b1c18',
          surface: '#252622',
          'surface-bright': '#5d5e67',
          'surface-variant': '#45464f',
          'on-surface-variant': '#c6c6d0',
          primary: '#b5c4ff',
          'primary-darken-1': '#8fa7fd',
          secondary: '#e8c423',
          'secondary-darken-1': '#caa900',
          error: '#ffb3af',
          info: '#9ecaff',
          success: '#78dc77',
          warning: '#FB8C00',
          'on-primary': '#052979',
          'primary-container': '#264190',
          'on-primary-container': '#dce1ff',
          'on-secondary': '#3b2f00',
          'secondary-container': '#554600',
          'on-secondary-container': '#ffe171',
          tertiary: '#82cfff',
          'on-tertiary': '#00344b',
          'tertiary-container': '#004c6b',
          'on-tertiary-container': '#c6e7ff',
          'on-background': '#e3e3db',
          'on-surface': '#d8d7d0',
          'on-surface-bright': '#b8b8c2',
          'on-error': '#68000e',
          'error-container': '#930018',
          'on-error-container': '#ffb3af',
          'on-success': '#00390a',
          'success-container': '#005313',
          'on-success-container': '#94f990',
          warn: '#ffb77b',
          'on-warn': '#4c2700',
          'warn-container': '#6d3a00',
          'on-warn-container': '#ffdcc2',
          'on-info': '#003258',
          'info-container': '#00497d',
          'on-info-container': '#d1e4ff',
        },
        variables: {
          'border-color': '#FFFFFF',
          'border-opacity': 0.12,
          'high-emphasis-opacity': 1,
          'medium-emphasis-opacity': 0.7,
          'disabled-opacity': 0.5,
          'idle-opacity': 0.1,
          'hover-opacity': 0.04,
          'focus-opacity': 0.12,
          'selected-opacity': 0.08,
          'activated-opacity': 0.12,
          'pressed-opacity': 0.16,
          'dragged-opacity': 0.08,
          'theme-kbd': '#212529',
          'theme-on-kbd': '#FFFFFF',
          'theme-code': '#343434',
          'theme-on-code': '#CCCCCC',
        },
      },
    }

  }
})
